### PR TITLE
Instance counter

### PR DESCRIPTION
**Pull request by jakepenn**

### CODE REVIEW

**Comment by jakepenn** [comment]
yikes, i thought i was pointing to the local modules but maybe when i pulled master the path changes to the SDK folder. Anyways, just a tiny pull request which adds a little instance counter to handle the multiple instances crash.

**Comment by spencersalazar** [comment]
This PR seems to change 450 separate files, most of which seem to be reverting to an older (2015) version of JUCE. I was going to suggest we clean this up before merging, or at least try to understand why there are so many changes here. Otherwise we will go crazy keeping everything in sync and having a sane git history.

**Comment by jakepenn** [comment]
Hey.. sorry about that.. I think maybe I actually pointed it to the juce modules local to the project which caused that, but it got merged. When i cloned the repo it was pointing to an external set of modules 

I added one more thing to disable the editor if it's the second instance. but do you want me to just revert the whole thing and then re add it later?

**Comment by spencersalazar** [comment]
I'll leave it up to you guys to decide how you want to move forward- but yeah lets just aim to keep things clean in general :)

**Pull request merged**
